import Head from 'next/head';
import { useQuery, gql } from '@apollo/client';

export default function Home() {
  const { data, loading, error } = useQuery(gql`
    query GetProductList {
      products {
        id
        slug
        name
        description
        price
        images {
          width
          height
          url
        }
      }
    }
  `);

  console.log(data, loading, error);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Dashboard</div>
    </div>
  );
}
